site_name: AutoNeuroNet
theme:
  name: material
  logo: assets/autoneuronet.svg
  favicon: assets/autoneuronet.svg
  palette:
    primary: light blue
    accent: yellow
nav:
  - Home: index.md
  - Install: install.md
  - Quickstart: quickstart.md
  - API: api.md
plugins:
  - mkdocstrings
